const express = require('express');
const controller = require('../controllers/bookController');
const { listComments, createComment } = require('../controllers/commentController');
const { identify, protect, authorize } = require('../middleware/auth');
const upload = require('../middleware/upload');
const catalog = require('../controllers/catalogController');

const router = express.Router();
router.get('/', identify, controller.listBooks);
router.get('/categories', controller.listCategories);
router.get('/stats', protect, authorize('admin', 'manager', 'employee'), controller.getBookStats);
router.get('/mine', protect, controller.listMyBooks);
router.get('/external/search', protect, authorize('admin', 'manager', 'employee'), catalog.searchExternalCatalog);
router.post('/external/import', protect, authorize('admin', 'manager', 'employee'), catalog.importExternalBook);
router.post('/upload', protect, upload.fields([{ name: 'bookFile', maxCount: 1 }, { name: 'coverImage', maxCount: 1 }]), catalog.uploadBook);
router.get('/:id', identify, controller.getBook);
router.get('/:id/comments', controller.listComments || listComments);
router.post('/:id/comments', protect, createComment);
router.post('/', protect, controller.createBook);
router.patch('/:id/review', protect, authorize('admin', 'manager', 'employee'), controller.reviewBook);
router.patch('/:id', protect, authorize('admin', 'manager', 'employee'), controller.updateBook);
router.delete('/:id', protect, authorize('admin'), controller.deleteBook);
module.exports = router;
